/*
===============================================================
 #CUSTOM JavaScript
- Please do not edit this file. This file is generated from admin area.
- Every changes here will be overwritten by theme
===============================================================*/
    /* theme_options_custom 
=========================*/
 document.querySelectorAll(".col-theme-icons .elementor-icon").forEach(link => {
  link.addEventListener("focus", () => link.closest('.elementor-widget-container').classList.toggle("focus"));
  link.addEventListener("blur", () => link.closest('.elementor-widget-container').classList.toggle("focus"));
 });
