name: Find and Replace

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.PAT }}
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "https://wordpress.dev.geo.ca/wordpress/"
        replace: "https://dev.geo.ca/"
        regex: true
    
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Commit
        branch: dev