name: Find and Replace

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate
      uses: actions/checkout@v3
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: /https://wordpress.dev.geo.ca/wordpress//g
        replace: "https://dev.geo.ca/"
        regex: true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: dev