name: Dev Deployment

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace URL
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "https://wordpress.dev.geo.ca/wordpress/"
          replace: "https://dev.geo.ca/"
          regex: false
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0