name: Find and Replace

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate
      uses: actions/checkout@v3
    
    #- name: Find and Replace
    #  uses: jacobtomlinson/gha-find-replace@v3
    #  with:
    #    find: ""
    #    replace: "https://dev.geo.ca/"
    #    regex: true
    
    - name: Find & Replace
      id: URL
      uses: ashley-taylor/regex-property-action@v1.3
      with:
        value: "https://dev.geo.ca/"
        regex: "https://wordpress.dev.geo.ca/wordpress/"
        flags: "g" # Optional, defaults to "g"
        replacement: "universe"

    - name: Print Result
      run: echo "${{ steps.URL.outputs.value }}"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: dev