name: Find and Replace Prod Deployment

on:
  push:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate - Prod
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: prod
    
    - name: Find and Replace - Prod
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "https://stage.geo.ca/"
        replace: "https://geo.ca/"
        regex: true
        exclude: "**/*.yml"
    
    - name: Push changes - Prod
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Commit - Prod
        push_options: --force
        branch: prod