name: Find and Replace Prod Deployment

on:
  push:
    branches: [ prod ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate - Prod
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: prod
    
    - name: Find and Replace - Prod
      run: |
        find -not -path './.git*' -type f -exec sed -i 's/app-stage.geo.ca/app.geo.ca/g' {} \;
        find -not -path './.git*' -type f -exec sed -i 's/stage.geo.ca/geo.ca/g' {} \;
        find -not -path './.git*' -type f -exec sed -i 's/geocore-stage.api.geo.ca/geocore.api.geo.ca/g' {} \;
    
    - name: Push changes - Prod
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Commit - Prod
        push_options: --force
        branch: prod 