name: Find and Replace Stage Deployment

on:
  push:
    branches: [ stage ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate - Stage
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: stage
   
    - name: Find and Replace - Stage
      run: |
        find -not -path './.git*' -type f -exec sed -i 's/app-dev.geo.ca/app-stage.geo.ca/g' {} \;
        find -not -path './.git*' -type f -exec sed -i 's/dev.geo.ca/stage.geo.ca/g' {} \;
        find -not -path './.git*' -type f -exec sed -i 's/geocore-dev.api.geo.ca/geocore-stage.api.geo.ca/g' {} \;
    
    - name: Push changes - Stage
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Commit - Stage
        push_options: --force
        branch: stage
    
    - name: Push changes - Init Prod
      run: git push origin -f stage:prod