name: Find and Replace Stage Deployment

on:
  push:
    branches: [ stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initiate - Stage
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: stage
    
    - name: Find and Replace - Stage
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "https://dev.geo.ca/"
        replace: "https://stage.geo.ca/"
        regex: true
        exclude: "**/*.yml"

    - name: Find and Replace - Geocore - Stage
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "https://geocore-dev.api.geo.ca/"
        replace: "https://geocore-stage.api.geo.ca/"
        regex: true
        exclude: "**/*.yml"
    
    - name: Push changes - Stage
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Commit - Stage
        push_options: --force
        branch: stage
    
    - name: Push changes - Init Prod
      run: git push origin -f stage:prod